### ISSUE TITLE
Suggestion: send check run statuses to github without creating a "job sandwich"

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-utils#12]
Currently, sending check request statuses to github involves building a "job sandwich." One job signals that the job you actually want to run is in-progress, then the job you wanted to run runs, then another job signals success or failure...

Can we go keto and cut out the bread in this job sandwich? If this library could send the statuses directly to github instead of spawning jobs to accomplish that, it would really cut down on the noise for any given build.

iirc, i had asked @technosophos about this once before and he said it had been considered, but the ultimate conclusion was that github-specific behavior didn't belong in brigadier. Fair enough. But this behavior seems very much appropriate for this utils library.

**Comment by radu-matei** [comment]
A couple of thoughts on this idea:

- I would very much like _not_ to pollute the list with two additional jobs for communicating with GitHub
- currently, the [`check-run` functionality is implemented in Go](https://github.com/brigadecore/brigade-github-app/blob/master/cmd/check-run/main.go), and just reads all the fields from environment variables, gets the OAuth token, then sends the request to the Checks API before, and after the actual jobs.

- here's what we have as a best practice (and of course, I'm biased here, since I wrote that part..)

> As we have seen, it is easy to add new functionality to the Brigade worker. But it is important to keep in mind that the Worker is intended to do one thing: execute Brigade chains.

> To that end, it is best to fight the temptation to put too much logic into the Brigade worker. Where possible, use Jobs to perform specific tasks within their own containers, and use workers to control the execution of a series of Jobs.

Conceptually, we've always tried _not_ to include actual application logic in `brigade.js`, and, whenever possible, delegate that to jobs - and that seems to have worked quite well so far. 

That being said, there are also examples we've seen where adding application logic to `brigade.js` makes things exponentially easier (see [the preview environments tutorial](https://docs.brigade.sh/intro/tutorial-preview-environments/)), and this is the reason for adding custom worker dependencies in the first place, so I'm open to exploring this approach.

- if we were to explore it, then the `send` function for a `Notification` object from this library would then have to replicate the `check-run` implementation and:
  - set the correct payload
  - acquire the token - see https://github.com/brigadecore/brigade-github-app/blob/master/pkg/webhook/client.go#L155-L164
  - send the request

Then, the `wrap` function would be unmodified, as well as the `Check` implementation here. Other things to consider:

- adding the GitHub client library API as dependency to this package
- adding an OAuth dependency as well (for acquiring the token - see https://github.com/brigadecore/brigade-github-app/blob/master/pkg/webhook/client.go#L155-L164)

I'd really like to see a working demo of this!

**Comment by krancour** [comment]
> To that end, it is best to fight the temptation to put too much logic into the Brigade worker.

I don't philosophically object to that point of view, but construction of the notification sandwich is _already_ its own kind of specialized logic that would seem to defy this tenet. Practically speaking, isn't the question of job execution vs function call only a minor implementation detail in that existing logic?

> I'd really like to see a working demo of this!

Awesome! I'd love to work on this myself, but am worried my JS isn't strong enough. There may, however, be some prior art that I can use as inspiration here. I'll at least take a look.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.

Also note that this discussion was factored into the Brigade v2, where new features were added that allow _gateways_ to monitor the status of events they created so they can take on responsibility for reporting upstream to the original source of the event, if pertinent. In general, smarter gateways obviate the need _both_ for a "job sandwich" or libraries that tackle the issue in userland.
